/* Static facts and texture mapping for the Orrery field guide. */
const DATA=[
 ['Sun','STAR','5800 K','274 m/s²','The star at the heart of our system, holding everything in orbit.','Light takes 8 minutes 20 seconds to reach Earth.','2k_sun.jpg',3.7],
 ['Mercury','PLANET','3.30 × 10²³ kg','3.70 m/s²','A small, scarred world of extremes, closest to the Sun.','A year on Mercury lasts just 88 Earth days.','2k_mercury.jpg',.55],
 ['Venus','PLANET','4.87 × 10²⁴ kg','8.87 m/s²','A cloud-shrouded world with the hottest surface in the system.','One day on Venus is longer than its year.','2k_venus_surface.jpg',.95],
 ['Earth','PLANET','5.97 × 10²⁴ kg','9.81 m/s²','Our blue home: an ocean world alive with a thin, protective atmosphere.','Earth is the only planet known to harbor life.','2k_earth_daymap.jpg',1],
 ['Moon','MOON','7.35 × 10²² kg','1.62 m/s²','Earth’s constant companion, shaped by ancient impacts.','The Moon is slowly drifting away from Earth.','2k_moon.jpg',.28],
 ['Mars','PLANET','6.42 × 10²³ kg','3.71 m/s²','A rust-red desert world with the largest volcano we know.','Olympus Mons rises nearly three times higher than Everest.','2k_mars.jpg',.7],
 ['Jupiter','PLANET','1.90 × 10²⁷ kg','24.79 m/s²','A stormy giant whose gravity shepherds the outer system.','The Great Red Spot has raged for centuries.','2k_jupiter.jpg',2.5],
 ['Saturn','PLANET','5.68 × 10²⁶ kg','10.44 m/s²','A pale gas giant wrapped in a spectacular architecture of ice.','Saturn’s rings are younger than the planet itself.','2k_saturn.jpg',2.2],
 ['Uranus','PLANET','8.68 × 10²⁵ kg','8.69 m/s²','An ice giant rolling through space on its side.','Its blue-green color comes from atmospheric methane.','2k_uranus.jpg',1.65],
 ['Neptune','PLANET','1.02 × 10²⁶ kg','11.15 m/s²','A deep-blue ice giant lashed by the fastest winds measured.','Neptune takes 165 years to orbit the Sun.','2k_neptune.jpg',1.6],
 ['Pluto','DWARF PLANET','1.31 × 10²² kg','0.62 m/s²','A bright-hearted dwarf planet at the edge of the known system.','Pluto and its moon Charon orbit a shared point in space.','pluto.jpg',.5]
];
const canvas=document.querySelector('#space'),rail=document.querySelector('#objectRail'),loading=document.querySelector('#loading'),fallback=document.querySelector('#fallback');
let selected=3,factsOn=true,scene,camera,meshes=[],travelTarget=null,dragging=false,lastPointer=null;
const $=id=>document.getElementById(id);
DATA.forEach((d,i)=>{const b=document.createElement('button');b.type='button';b.textContent=String(i+1).padStart(2,'0');b.title=`View ${d[0]}`;b.setAttribute('aria-label',`View ${d[0]}`);b.onclick=()=>select(i);rail.appendChild(b)});
function updateInfo(i){const d=DATA[i];$('infoType').textContent=`${d[1]} · ${String(i+1).padStart(2,'0')} / ${DATA.length}`;$('infoName').textContent=d[0];$('infoMass').textContent=d[2];$('infoGravity').textContent=d[3];$('infoDescription').textContent=d[4];$('infoFunFact').textContent=factsOn?`✦ ${d[5]}`:'';[...rail.children].forEach((b,n)=>b.setAttribute('aria-current',n===i?'true':'false'))}
function select(i){selected=i;updateInfo(i);if(camera&&meshes[i]){const m=meshes[i];travelTarget={position:m.position.clone(),radius:Math.max(4,m.scaling.x*7)}}}
$('factsToggle').onclick=()=>{factsOn=!factsOn;$('factsToggle').setAttribute('aria-pressed',factsOn);$('factsToggle').innerHTML=`FUN FACTS <span>${factsOn?'ON':'OFF'}</span>`;updateInfo(selected)};
document.addEventListener('keydown',e=>{if(e.key==='ArrowDown'||e.key==='ArrowRight')select((selected+1)%DATA.length);if(e.key==='ArrowUp'||e.key==='ArrowLeft')select((selected+DATA.length-1)%DATA.length);if(e.key==='Home')select(0);if(e.key==='End')select(DATA.length-1)});
function texture(B,path,scene){return new B.Texture(`textures/${path}`,scene)}
function quietMaterial(B,mat){mat.specularColor=new B.Color3(0,0,0);mat.specularPower=4;/* Gentle bounce light keeps the terminator from becoming a hard cut. */mat.emissiveColor=new B.Color3(.035,.035,.035);return mat}
function addEarthLayers(B,scene){
  const earth=meshes[3];
  const clouds=B.MeshBuilder.CreateSphere('earth-clouds',{segments:32,diameter:1.012},scene);clouds.parent=earth;const cloudMat=quietMaterial(B,new B.StandardMaterial('earth-cloud-material',scene));cloudMat.diffuseTexture=texture(B,'2k_earth_clouds.jpg',scene);cloudMat.opacityTexture=cloudMat.diffuseTexture;cloudMat.alpha=.34;cloudMat.backFaceCulling=false;clouds.material=cloudMat;
  const night=B.MeshBuilder.CreateSphere('earth-night-diffuse',{segments:32,diameter:1.008},scene);night.parent=earth;const nightMat=quietMaterial(B,new B.StandardMaterial('earth-night-material',scene));nightMat.emissiveTexture=texture(B,'2k_earth_nightmap.jpg',scene);nightMat.alpha=.28;nightMat.backFaceCulling=false;night.material=nightMat;
  const earthMat=earth.material;earthMat.bumpTexture=texture(B,'2k_earth_normal_map.png',scene);earthMat.specularTexture=texture(B,'2k_earth_specular_map.png',scene);earthMat.specularColor=new B.Color3(.18,.18,.18);earthMat.specularPower=8;
}
function boot(){if(!window.BABYLON||!BABYLON.Engine.isSupported()){fallback.hidden=false;loading.classList.add('done');$('status').textContent='WEBGL UNAVAILABLE';return}try{const B=BABYLON,engine=new B.Engine(canvas,true,{preserveDrawingBuffer:false,stencil:true});scene=new B.Scene(engine);scene.clearColor=new B.Color4(0,0,0,1);camera=new B.ArcRotateCamera('navigator',Math.PI/2.2,Math.PI/2.4,14,B.Vector3.Zero(),scene);camera.attachControl(canvas,true);camera.wheelPrecision=45;camera.lowerRadiusLimit=2;camera.upperRadiusLimit=120;new B.HemisphericLight('ambient',new B.Vector3(0,1,0),scene).intensity=.12;const glow=new B.PointLight('sunlight',B.Vector3.Zero(),scene);glow.intensity=20;glow.range=80;const sun=B.MeshBuilder.CreateSphere('sun',{diameter:3.2},scene);const sunMat=new B.StandardMaterial('sunmat',scene);sunMat.emissiveTexture=texture(B,'2k_sun.jpg',scene);sun.material=sunMat;meshes[0]=sun;DATA.slice(1).forEach((d,idx)=>{const i=idx+1,m=B.MeshBuilder.CreateSphere(d[0],{segments:32,diameter:d[7]},scene);m.position=new B.Vector3(Math.cos(idx*.64)*(5+idx*.9),Math.sin(idx*.8)*.8,Math.sin(idx*.64)*(5+idx*.9));const mat=quietMaterial(B,new B.StandardMaterial(`${d[0]}mat`,scene));mat.diffuseTexture=texture(B,d[6],scene);m.material=mat;meshes[i]=m});addEarthLayers(B,scene);const stars=B.MeshBuilder.CreateSphere('stars',{diameter:180,sideOrientation:B.Mesh.BACKSIDE},scene);const sm=new B.StandardMaterial('starmat',scene);sm.emissiveTexture=texture(B,'2k_stars_milky_way.jpg',scene);stars.material=sm;canvas.addEventListener('pointerdown',e=>{dragging=true;lastPointer={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragging||!meshes[selected])return;const dx=e.clientX-lastPointer.x,dy=e.clientY-lastPointer.y;meshes[selected].rotation.y+=dx*.01;meshes[selected].rotation.x+=dy*.01;lastPointer={x:e.clientX,y:e.clientY}});canvas.addEventListener('pointerup',()=>{dragging=false});scene.registerBeforeRender(()=>{if(travelTarget){camera.target=B.Vector3.Lerp(camera.target,travelTarget.position,.045);camera.radius+=(travelTarget.radius-camera.radius)*.045;if(B.Vector3.Distance(camera.target,travelTarget.position)<.01&&Math.abs(camera.radius-travelTarget.radius)<.01)travelTarget=null}meshes.forEach((m,i)=>{if(m&&i!==selected)m.rotation.y+=.0002})});engine.runRenderLoop(()=>scene.render());addEventListener('resize',()=>engine.resize());updateInfo(selected);select(selected);loading.classList.add('done')}catch(err){console.error(err);fallback.hidden=false;loading.classList.add('done');$('status').textContent='SCENE ERROR'}}boot();
// Camera gestures remain enabled; selected bodies keep a fixed orientation.
if(scene)scene.registerBeforeRender(()=>meshes.forEach(m=>{if(m)m.rotation.set(0,0,0)}));
